### ISSUE TITLE
Work out discussion system

### ISSUE THREAD

**Issue by frabcus** [redecentralize/redecentralize-website#11]
We want to form a community talking about redecentralization. 

Research what works for podcasts to form a good discussion community and do it. eg Disqus comments on each interview page.

**Comment by shevski** [comment]
Forum / mailing list

**Comment by frabcus** [comment]
We're trying Disqus comments, will see how it goes.

**Comment by frabcus** [comment]
I don't think Disqus has worked out for us yet - need a bit of a better strategy than just throwing it up. I suggest we remove it and try other things.
