### ISSUE TITLE
Adam Ierymenko link in opening paragraph of blurb points to ntoll

### ISSUE THREAD

**Issue by ntoll** [redecentralize/redecentralize-website#13]
Hi,

"Adam Ierymenko talks about ZeroTier One, which creates flat virtual Ethernet networks of almost unlimited size. He describes how this lets people experiment with new ways of using networking."

The "Adam Ierymenko" link points to me instead of his home page / twitter account. Since I don't know what the correct value for this should be I can't submit a patch.

Pretty certain you know what to do though... ;-)

N.

**Comment by frabcus** [comment]
Fixed, thanks for reporting!
