### ISSUE TITLE
Output mp3 version of interviews

### ISSUE THREAD

**Issue by shevski** [redecentralize/redecentralize-website#16]
For listening only.
@johnmartin we have mp4, do we need the mp3s?

**Comment by johnmartin** [comment]
If you are wanting to do a audio podcast: yes.

**Comment by frabcus** [comment]
What platform does it matter on?

I'd assumed that most platforms would still play an mp4, even if the user
isn't looking at the video.

**Comment by shevski** [comment]
Old (non ipod) mp3 players won't be able to play them.

I think it's fine for phones and for apple products

**Comment by frabcus** [comment]
Ok... Would they be using the RSS feed then? Need to know where to link to
the mp3 from.

**Comment by navinpai** [comment]
It would be great if audio links could be made available to people in a manner similar to how TED does it: http://www.ted.com/talks/ken_robinson_says_schools_kill_creativity.html (The download button offers the audio option as well). Especially since the interviews are very podcast-like, it'll be useful for people just preferring to listen to the interview

Great job btw :+1:

**Comment by JonTheNiceGuy** [comment]
If you've got the M4V (MP4 video) files, you can use mplayer to strip out just the audio. You should re-encode to Opus, OggVorbis, MP3 and M4A.

Opus is a variable bitrate audio format, championed by Skype and Mumble.
OggVorbis is the FLOSS file type of choice (right now - it might become Opus soon though)
M4A is the iTunes format of choice
MP3 is a fall-back for the above.

Opus, OggVorbis, M4V and M4A all permit chapter marks. MP3 does not.

**Comment by frabcus** [comment]
Hi John!
1. Can you tell me a bit more about how and with what software you would
   use audio only?

We have lots of subscribe buttons already, and want them to all be
meaningful.

What kind of feed or interface would they go in?
1. We currently have webm as our open format, to go with the mp4 that
   iTunes needs. For video, is that open enough?

**Comment by JonTheNiceGuy** [comment]
Hi @frabcus 

Sure, so I don't know what platform you're using, but I'll assume you're using Linux (as most of these tools will be cross-platform)

To support the iTunes people, we'll use AAC there, as it's the audio container typically used in M4V. Use ffmpeg or mplayer [1] to get the AAC file out of the M4V file.

To support the Linux people, we'll use OggVorbis, which is the default audio container in WebM, so let's use ffmpeg there too [2]. And, from there, you can get to MP3 using ffmpeg too [3]. You can convert any of these formats to Opus [4].

[1] http://ubuntuforums.org/showthread.php?t=1122611
[2] http://ubuntuforums.org/showthread.php?t=1912289
[3] http://iamyouruser.blogspot.co.uk/2009/06/ubuntu-convert-ogg-to-mp3.html
[4] http://askubuntu.com/questions/211054/how-to-convert-a-sound-file-to-opus

Typically, I would change your "subscribe" list as follows:

```
Subscribe
|
+-- Video
|   +-- Subscribe using iTunes (iTunes Link to m4v RSS)
|   +-- Subscribe using YouTube (Link to YouTube Channel)
|   +-- Subscribe to Watch on Firefox/Chrome/Android (Link to WebM RSS)
|   +-- Subscribe to Watch on Safari/Internet Explorer/iPhone/iPad/iPod (Link to M4V RSS)
+-- Audio
|   +-- Subscribe using iTunes (iTunes link to AAC RSS)
|   +-- Subscribe to listen using Windows/Linux/Android (Link to OggVorbis)
|   +-- Subscribe to listen using Mac/iPhone/iPad/iPod (Link to AAC RSS)
|   +-- Subscribe to listen to Opus (Link to Opus RSS)
+-- Text
    +-- Join our mailing list (Link to mailing list)
    +-- Follow us on Twitter (Link to twitter.com/redecentralize)
```

I would suggest that your RSS feeds are structured like this:
http://redecentralize.org/podcast/{FORMAT}.rss
With one exception - keep the existing URL (http://redecentralize.org/podcast/feed.rss) as the MP4 format

The WebM format is definitely open enough.

I hope this helps!

**Comment by frabcus** [comment]
Thanks @JonTheNiceGuy! Just checking - can I not put multiple types (of, say audio) in one RSS feed, with different enclosure mime types?

**Comment by frabcus** [comment]
Also, any particular reason to not just use MP3 for all audio? Does iTunes not support it?

**Comment by JonTheNiceGuy** [comment]
MP3 is patent encumbered. While there are Free (as in freedom) software implementations of the MP3 encoder and decoder, in many regions of the world (notably the USA) you are not permitted to use those encoders and decoders without paying a license fee, and as a result, many Free Software developers refuse to use the MPEG codecs. See http://en.wikipedia.org/wiki/MP3#Licensing_and_patent_issues for details.

Sadly, as Apple are a major stakeholder in the MPEG world, they will only ship MPEG based codecs (MP4, AAC, etc) and will not use the Free alternatives (OggVorbis, OggTheora, WebM, Opus) - hence needing the various streams.

Also, subsequent formats (AAC, Vorbis and Opus) permit a greater array of metadata about the file, including, in particular, chapter marks - should that be appropriate at a later point.

With regards to the "Various mime types" question, while it's in the spec, I've not yet seen a reader which actually parses the options, and offers you the "right" one. You could use the MRSS namespace (See here: http://www.rssboard.org/media-rss for details) but as far as I can tell, it's not been widely adopted (This wiki article http://en.wikipedia.org/wiki/Media_RSS only lists 4 players which adopted it).
