### ISSUE TITLE
Provide transcripts

### ISSUE THREAD

**Issue by frabcus** [redecentralize/redecentralize-website#22]
"While this is a subject I would be interested in, I took one look at the front page, saw that it appeared to be video-only, and gave up.
This is precisely the reaction that news sites get from me when I click on a link to a story and find video-only content.
Am I the only one, or would it be a really good idea to provide transcripts of the interviews?"

https://news.ycombinator.com/item?id=6544184

**Comment by frabcus** [comment]
Two people have volunteered to help with this

**Comment by frabcus** [comment]
We're now organizing this on this spreadsheet: https://docs.google.com/spreadsheet/ccc?key=0Aqv-CMqMTudXdEFJUnlRbmJFb3hYcDQyN2NzUHl1TWc#gid=0

Have a look and sign up to do a transcript if you want to help!

**Comment by davidhfo** [comment]
A couple of thoughts:

1) Have a separate web feed that is text-only. That way, those who prefer the text will not be notified of a new video, come and see there's no text, and then have to remember to check back later and see if it's up. They would only be notified when the text version is available.
And when someone does happen upon a video when there isn't a transcription yet, there could be a notice just next to the video, pointing them to the text RSS feed, and explaining that the text would be up soon.

2) Delay the posting of the next interview for a few days until a transcription is done, so both can be put up at once. You could, as soon as you have a possible interview date, email those who've done transcripts before, letting them know when the next video would be recorded and ready, to see who might be available at that time and want to take ownership.
