### ISSUE TITLE
Change from Github to gitlab or similar

### ISSUE THREAD

**Issue by frabcus** [redecentralize/redecentralize-website#23]
Is there one that decentralizes issues as well as code?

And we'd need to do the jekyll page generation stuff.

http://gitlab.org/

Comment suggesting this: https://news.ycombinator.com/item?id=6544212

**Comment by peakwinter** [comment]
Hi guys!

I have a running Gitlab instance that I use for the CitizenWeb Project. I'd be happy to answer questions, let you sign up and poke around to learn the ropes, or you can even freely use it for redecentralize if you don't want to end up having to host an instance yourselves (it takes a pretty significant amount of resources).

Let me know! All the best,
- J

**Comment by frabcus** [comment]
Not going to fix this for now, sorry!
