### ISSUE TITLE
Get Involved

### ISSUE THREAD

**Issue by rossjones** [redecentralize/redecentralize-website#27]
We need a page to let people know how they can get involved. With details of the mailing list etc.

**Comment by frabcus** [comment]
There's a section on the right hand side of the about page which links
to the wiki.

You think it needs a special web page?

On Thu, Dec 19, 2013 at 02:31:39AM -0800, Ross Jones wrote:

> We need a page to let people know how they can get involved. With details of the mailing list etc.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/redecentralize/redecentralize-website/issues/27

## 

Do _you_ have an awesome idea you never quite manage to do? 
http://www.awesomefoundation.org/en/chapters/liverpool/

**Comment by rossjones** [comment]
I was thinking Meetups and Mailing list as well with a prominent CTA somewhere.

**Comment by frabcus** [comment]
Certainly something can be really well designed and more usable than
we have now.

On Thu, Dec 19, 2013 at 02:57:04AM -0800, Ross Jones wrote:

> I was thinking Meetups and Mailing list as well with a prominent CTA somewhere.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/redecentralize/redecentralize-website/issues/27#issuecomment-30920388

## 

Do _you_ have an awesome idea you never quite manage to do? 
http://www.awesomefoundation.org/en/chapters/liverpool/
