### ISSUE TITLE
Use HTTPS

### ISSUE THREAD

**Issue by konklone** [redecentralize/redecentralize-website#44]
It looks like the site's not on Github Pages, but self-hosted (naturally). So, the site should use HTTPS (as should everything).

If it's helpful, I have a [howto](https://konklone.com/post/switch-to-https-now-for-free) which covers a few things. 
1. How to get a free class 1 cert from StartSSL (which this organization may or may not qualify for, it's meant for individual non-commercial activity)
2. How to generate a certificate request for any certificate provider
3. Example nginx configuration with secure settings
4. General discussion of what the settings mean and how to accomplish them in non-nginx settings

**Comment by livmackintosh** [comment]
:+1: If using Apache and Debian based system, you can use https://letsencrypt.org/ :smile_cat:

**Comment by olizilla** [comment]
@frabcus do you have the keys to the DNS kingdom? We can enable HTTPS today on github pages, but we need to update the A records as per https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by frabcus** [comment]
First a side note - there is also a staging.redecentralize.org which serves https://github.com/redecentralize/redecentralize-website-staging/ - I'm making changes to that first. It's currently set to force HTTPS to test that, and is serving an error as Github hasn't made the new cert.

I made the DNS changes for staging, which worked fine. The ones for www are now propagating.

I've also kicked Github Pages by removing and adding the domains on the two repositories. This will hopefully coerce it into making new certificates.

Will come back later to see how it's going...

**Comment by frabcus** [comment]
Most of this has propagated, and I've turned on HTTPS forcing for the main domain.

These three things still seem broken:

* [ ] http://redecentralise.org/ (with an S) is giving me a 404 due to DNS not propagated (an ANAME record I made for a bit by accident).  It's meant to point to one of our servers on Bytemark that does the redirect.
* [ ] https://www.redecentralize.org/ (gone straight to) is complaining about certificates. Is there something special to do to make it generate the cert for www? (It's using the redirect in https://help.github.com/articles/setting-up-an-apex-domain-and-www-subdomain/)
* [ ] https://redecentralise.org/ won't work via the Bytemark server, as we're not making certs there. This is fixable but seems a bit beyond scope for now.

**Comment by frabcus** [comment]
Yeah turns out they don't make certs yet for the www. subdomain, as described in https://github.community/t5/GitHub-Pages/Does-GitHub-Pages-Support-HTTPS-for-www-and-subdomains/td-p/7116

This isn't a big issue for us as we don't use it. I assume it will self correct one day.

**Comment by Treora** [comment]
I updated our Bytemark server and fixed some things, now using a docker-compose+traefik setup to ease maintenance and tls certificate provisioning (using letsencrypt).

> These three things still seem broken:
> 
> * [ ]  http://redecentralise.org/ (with an S) is giving me a 404 due to DNS not propagated (an ANAME record I made for a bit by accident).  It's meant to point to one of our servers on Bytemark that does the redirect.

Fixed now.
 
> * [ ]  https://www.redecentralize.org/ (gone straight to) is complaining about certificates. Is there something special to do to make it generate the cert for www? (It's using the redirect in https://help.github.com/articles/setting-up-an-apex-domain-and-www-subdomain/)

GitHub [appears][1] not to support this. So I pointed the 'www' subdomain to our server too, which then does the redirect (i.e. removing the 'www').

> * [ ]  https://redecentralise.org/ won't work via the Bytemark server, as we're not making certs there. This is fixable but seems a bit beyond scope for now

Fixed now.

Also I enabled certificate provision for `something.redecentralize.org`, and updated this website to use https to point to all the videos hosted there.

A next step would be to move the site off GitHub Pages and self-host it (naturally, indeed); but I suppose this current issue can be closed.

[1]: https://github.community/t/does-github-pages-support-https-for-www-and-subdomains/10360
