### ISSUE TITLE
Use some kind of analytics on the podcast RSS feed

### ISSUE THREAD

**Issue by frabcus** [redecentralize/redecentralize-website#6]
So we can measure number of subscribers

**Comment by frabcus** [comment]
I've got basic numbers by grepping the server logs for the videos. Which has the advantage it also detects people watching via the website.

**Comment by frabcus** [comment]
@rossjones anything easy we can set up for this?

**Comment by rossjones** [comment]
We should have a piwik/openwebanalytics setup anyway. What we really want for feeds is feedburner, but I believe that's dead now, will see if there are any alternatives to it (even if it is just dump http headers to db and redirect).

**Comment by frabcus** [comment]
Yeah - is there something open source that does feed analytics?

On Tue, Nov 12, 2013 at 02:23:28AM -0800, Ross Jones wrote:

> We should have a piwik/openwebanalytics setup anyway. What we really want for feeds is feedburner, but I believe that's dead now, will see if there are any alternatives to it (even if it is just dump http headers to db and redirect).
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/redecentralize/redecentralize-website/issues/6#issuecomment-28282506

## 

Do _you_ have an awesome idea you never quite manage to do? 
http://www.awesomefoundation.org/en/chapters/liverpool/

**Comment by rossjones** [comment]
pwiki will do the site, for the feed analytics I am going to just have a proxy that throws the http headers of the request in a timeseries/document database (like influx) and then 302 the request onwards.
