### ISSUE TITLE
README: Clarify "Publishing a new interview" section

### ISSUE THREAD

**Issue by elimisteve** [redecentralize/redecentralize-website#69]
```
Publishing a new interview

Ideally get a transcript ahead of time by emailing the transcript person
a direct link to the (unlisted) video on Youtube.
```

I'd like to interview someone for a Redecentralize video.  Who is "the transcript person" and what does that mean?  Thanks!

**Comment by frabcus** [comment]
We don't have a transcript person at the moment - but it means somebody who is prepared to listen to the interview, and type up a transcript as text.

Lots of people prefer to read the interviews.

This step is optional - just go for it if you'd like to make a video!
