### ISSUE TITLE
Is the mailing list broken?

### ISSUE THREAD

**Issue by livmackintosh** [redecentralize/redecentralize-website#80]
I've tried subscribing to the mailing list but no replies :(

I'm not sure if the service is temporarily down but there hasn't been any posts from any list since October? It would be really amazing if there is some chat to use in the mean time, even an IRC room? :smile_cat: 

Liv

**Comment by frabcus** [comment]
It looks like it is broken - nobody's messages have got through since October.

I've contacted LibreList support.

**Comment by livmackintosh** [comment]
It's a shame because it seemed like a cool idea (to be able to reply) :)

**Comment by frabcus** [comment]
It's now over at https://groups.google.com/forum/#!forum/redecentralize - sorry it was down so long
