### ISSUE TITLE
Is webm still needed?

### ISSUE THREAD

**Issue by frabcus** [redecentralize/redecentralize-website#81]
It serves the videos in webm for some browsers, still needed or mp4 fine everywhere now?

**Comment by Treora** [comment]
I would actually expect this question the other way around. :) I think most mp4’s are encoded with the H.264 codec that has some patent issues around it; it might not even be playable out of the box on some platforms. I suggest we follow [FSF’s approach][1] of also providing these however, for the platforms that are stuck in the other way around.

[1]: https://www.fsf.org/blogs/community/the-fsfs-approach-to-using-online-videos-for-advocacy
